### ISSUE TITLE
Include CSS in component so user do not have to import it manually

### ISSUE THREAD

**Issue by GauthierPLM** [andrewvasilchuk/vue-lazy-youtube-video#11]
The CSS should be imported in the component directly so the user do not have to import it manually.

Currently, the component will not work if CSS is not imported in addition to the component. Moreover, this is not explained in the README.

**Comment by andrewvasilchuk** [comment]
@GauthierPLM, Thanks. It's by design. Currently `rollup-plugin-vue` does not support correct build for SSR. If we insert styles directly into component, an SSR build will be completely broken, so we are forced  tom move styles to the separate file, and bundle them independently.  Skim through this [issue](https://github.com/vuejs/rollup-plugin-vue/issues/266).

**Comment by andrewvasilchuk** [comment]
@GauthierPLM, There is a separate [section](https://github.com/andrewvasilchuk/vue-lazy-youtube-video#styles) about styles.
